-- Reference DDL for the LMS database (PostgreSQL 16).
-- Mirrors the JPA entities in backend/src/main/java/com/lms/entity.
-- In development Hibernate manages the schema (JPA_DDL_AUTO=update);
-- use this file for review, manual setup, or as a baseline migration.

-- Application role (STUDENT / INSTRUCTOR / ADMIN).
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE CHECK (name IN ('STUDENT', 'INSTRUCTOR', 'ADMIN')),
    description VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Application user. Each user has exactly one role.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE INDEX idx_users_role_id ON users (role_id);

-- A course owned by an instructor.
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    instructor_id BIGINT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_courses_instructor_id FOREIGN KEY (instructor_id) REFERENCES users (id)
);

CREATE INDEX idx_courses_instructor_id ON courses (instructor_id);

-- An ordered section of a course.
CREATE TABLE course_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_course_modules_course_id FOREIGN KEY (course_id) REFERENCES courses (id)
);

CREATE INDEX idx_course_modules_course_id ON course_modules (course_id);

-- A single learnable unit inside a module. Mastery is tracked per topic.
CREATE TABLE topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL DEFAULT 0,
    difficulty VARCHAR(30) NOT NULL DEFAULT 'MEDIUM' CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    estimated_minutes INTEGER,
    importance DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_topics_module_id FOREIGN KEY (module_id) REFERENCES course_modules (id)
);

CREATE INDEX idx_topics_module_id ON topics (module_id);

-- Directed edge: topic requires prerequisiteTopic.
CREATE TABLE topic_prerequisites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    prerequisite_topic_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_topic_prerequisites UNIQUE (topic_id, prerequisite_topic_id),
    CONSTRAINT fk_topic_prerequisites_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id),
    CONSTRAINT fk_topic_prerequisites_prerequisite_topic_id FOREIGN KEY (prerequisite_topic_id) REFERENCES topics (id)
);

CREATE INDEX idx_topic_prerequisites_topic_id ON topic_prerequisites (topic_id);
CREATE INDEX idx_topic_prerequisites_prerequisite_topic_id ON topic_prerequisites (prerequisite_topic_id);

-- Study material (video, article, PDF, ...) attached to a topic.
CREATE TABLE learning_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL CHECK (type IN ('VIDEO', 'ARTICLE', 'PDF', 'SLIDES', 'LINK', 'EXERCISE')),
    url VARCHAR(1000),
    content TEXT,
    difficulty VARCHAR(30) NOT NULL DEFAULT 'MEDIUM' CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    estimated_minutes INTEGER,
    order_index INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_learning_resources_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id)
);

CREATE INDEX idx_learning_resources_topic_id ON learning_resources (topic_id);

-- Multiple-choice question bank entry, instructor-written or AI-generated.
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    explanation TEXT,
    difficulty VARCHAR(30) NOT NULL DEFAULT 'MEDIUM' CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED')),
    created_by_type VARCHAR(30) NOT NULL DEFAULT 'INSTRUCTOR' CHECK (created_by_type IN ('INSTRUCTOR', 'AI')),
    created_by_id BIGINT,
    reviewed_by_id BIGINT,
    reviewed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_questions_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id),
    CONSTRAINT fk_questions_created_by_id FOREIGN KEY (created_by_id) REFERENCES users (id),
    CONSTRAINT fk_questions_reviewed_by_id FOREIGN KEY (reviewed_by_id) REFERENCES users (id)
);

CREATE INDEX idx_questions_topic_id ON questions (topic_id);
CREATE INDEX idx_questions_created_by_id ON questions (created_by_id);
CREATE INDEX idx_questions_reviewed_by_id ON questions (reviewed_by_id);

-- One answer choice of a question.
CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    order_index INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_question_options_question_id FOREIGN KEY (question_id) REFERENCES questions (id)
);

CREATE INDEX idx_question_options_question_id ON question_options (question_id);

-- A quiz. student is set only for personalised (adaptive/revision) quizzes.
CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    topic_id BIGINT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(30) NOT NULL DEFAULT 'PRACTICE' CHECK (type IN ('DIAGNOSTIC', 'PRACTICE', 'ASSESSMENT', 'REVISION', 'ADAPTIVE')),
    time_limit_minutes INTEGER,
    passing_score NUMERIC(5,2),
    created_by_type VARCHAR(30) NOT NULL DEFAULT 'INSTRUCTOR' CHECK (created_by_type IN ('INSTRUCTOR', 'AI')),
    created_by_id BIGINT,
    student_id BIGINT,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_quizzes_course_id FOREIGN KEY (course_id) REFERENCES courses (id),
    CONSTRAINT fk_quizzes_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id),
    CONSTRAINT fk_quizzes_created_by_id FOREIGN KEY (created_by_id) REFERENCES users (id),
    CONSTRAINT fk_quizzes_student_id FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE INDEX idx_quizzes_course_id ON quizzes (course_id);
CREATE INDEX idx_quizzes_topic_id ON quizzes (topic_id);
CREATE INDEX idx_quizzes_created_by_id ON quizzes (created_by_id);
CREATE INDEX idx_quizzes_student_id ON quizzes (student_id);

-- Join between quizzes and questions with ordering and weight.
CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0,
    points NUMERIC(6,2) NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_quiz_questions UNIQUE (quiz_id, question_id),
    CONSTRAINT fk_quiz_questions_quiz_id FOREIGN KEY (quiz_id) REFERENCES quizzes (id),
    CONSTRAINT fk_quiz_questions_question_id FOREIGN KEY (question_id) REFERENCES questions (id)
);

CREATE INDEX idx_quiz_questions_quiz_id ON quiz_questions (quiz_id);
CREATE INDEX idx_quiz_questions_question_id ON quiz_questions (question_id);

-- A student's single sitting of a quiz.
CREATE TABLE quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    submitted_at TIMESTAMP(6) WITH TIME ZONE,
    score NUMERIC(8,2),
    max_score NUMERIC(8,2),
    percentage NUMERIC(5,2),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_quiz_attempts_quiz_id FOREIGN KEY (quiz_id) REFERENCES quizzes (id),
    CONSTRAINT fk_quiz_attempts_student_id FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE INDEX idx_quiz_attempts_quiz_id ON quiz_attempts (quiz_id);
CREATE INDEX idx_quiz_attempts_student_id ON quiz_attempts (student_id);

-- A student's answer to one question within a quiz attempt. Primary ML feature source.
CREATE TABLE question_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option_id BIGINT,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    time_spent_seconds INTEGER,
    answered_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_question_attempts_quiz_attempt_id FOREIGN KEY (quiz_attempt_id) REFERENCES quiz_attempts (id),
    CONSTRAINT fk_question_attempts_question_id FOREIGN KEY (question_id) REFERENCES questions (id),
    CONSTRAINT fk_question_attempts_selected_option_id FOREIGN KEY (selected_option_id) REFERENCES question_options (id)
);

CREATE INDEX idx_question_attempts_quiz_attempt_id ON question_attempts (quiz_attempt_id);
CREATE INDEX idx_question_attempts_question_id ON question_attempts (question_id);
CREATE INDEX idx_question_attempts_selected_option_id ON question_attempts (selected_option_id);

-- Enrollment plus aggregate progress of a student in a course.
CREATE TABLE student_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    completion_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
    topics_completed INTEGER NOT NULL DEFAULT 0,
    total_study_minutes INTEGER NOT NULL DEFAULT 0,
    enrolled_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_accessed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_student_progress UNIQUE (student_id, course_id),
    CONSTRAINT fk_student_progress_student_id FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_student_progress_course_id FOREIGN KEY (course_id) REFERENCES courses (id)
);

CREATE INDEX idx_student_progress_student_id ON student_progress (student_id);
CREATE INDEX idx_student_progress_course_id ON student_progress (course_id);

-- Per-student knowledge state for a topic (mastery 0..1 and weak/strong classification).
CREATE TABLE student_topic_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    mastery_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    classification VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED' CHECK (classification IN ('NOT_STARTED', 'WEAK', 'NEEDS_PRACTICE', 'MODERATE', 'STRONG')),
    attempts_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    last_assessed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_student_topic_knowledge UNIQUE (student_id, topic_id),
    CONSTRAINT fk_student_topic_knowledge_student_id FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_student_topic_knowledge_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id)
);

CREATE INDEX idx_student_topic_knowledge_student_id ON student_topic_knowledge (student_id);
CREATE INDEX idx_student_topic_knowledge_topic_id ON student_topic_knowledge (topic_id);

-- A suggested topic/resource for a student, ranked by score.
CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    topic_id BIGINT,
    resource_id BIGINT,
    reason TEXT,
    score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    source VARCHAR(30) NOT NULL DEFAULT 'AI' CHECK (source IN ('INSTRUCTOR', 'AI')),
    viewed BOOLEAN NOT NULL DEFAULT FALSE,
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_recommendations_student_id FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_recommendations_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id),
    CONSTRAINT fk_recommendations_resource_id FOREIGN KEY (resource_id) REFERENCES learning_resources (id)
);

CREATE INDEX idx_recommendations_student_id ON recommendations (student_id);
CREATE INDEX idx_recommendations_topic_id ON recommendations (topic_id);
CREATE INDEX idx_recommendations_resource_id ON recommendations (resource_id);

-- A timed block of study activity.
CREATE TABLE study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    topic_id BIGINT,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP(6) WITH TIME ZONE,
    duration_minutes INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_study_sessions_student_id FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_study_sessions_course_id FOREIGN KEY (course_id) REFERENCES courses (id),
    CONSTRAINT fk_study_sessions_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id)
);

CREATE INDEX idx_study_sessions_student_id ON study_sessions (student_id);
CREATE INDEX idx_study_sessions_course_id ON study_sessions (course_id);
CREATE INDEX idx_study_sessions_topic_id ON study_sessions (topic_id);

-- Spaced-repetition schedule for a student/topic pair.
CREATE TABLE revision_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    stage VARCHAR(30) NOT NULL DEFAULT 'DAY_1' CHECK (stage IN ('DAY_1', 'DAY_3', 'DAY_7', 'DAY_14', 'DAY_30', 'MASTERED')),
    next_review_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_reviewed_at TIMESTAMP(6) WITH TIME ZONE,
    review_count INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_revision_schedules UNIQUE (student_id, topic_id),
    CONSTRAINT fk_revision_schedules_student_id FOREIGN KEY (student_id) REFERENCES users (id),
    CONSTRAINT fk_revision_schedules_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id)
);

CREATE INDEX idx_revision_schedules_student_id ON revision_schedules (student_id);
CREATE INDEX idx_revision_schedules_topic_id ON revision_schedules (topic_id);

-- Audit log of every AI request/response.
CREATE TABLE ai_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT,
    topic_id BIGINT,
    type VARCHAR(30) NOT NULL CHECK (type IN ('CHAT', 'EXPLANATION', 'HINT', 'SUMMARY', 'QUESTION_GENERATION', 'RECOMMENDATION')),
    prompt TEXT NOT NULL,
    response TEXT,
    model_name VARCHAR(100),
    input_tokens INTEGER,
    output_tokens INTEGER,
    latency_ms BIGINT,
    rating INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_interactions_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ai_interactions_course_id FOREIGN KEY (course_id) REFERENCES courses (id),
    CONSTRAINT fk_ai_interactions_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id)
);

CREATE INDEX idx_ai_interactions_user_id ON ai_interactions (user_id);
CREATE INDEX idx_ai_interactions_course_id ON ai_interactions (course_id);
CREATE INDEX idx_ai_interactions_topic_id ON ai_interactions (topic_id);

-- Uploaded course material that the RAG service ingests.
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    topic_id BIGINT,
    uploaded_by_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    file_size BIGINT,
    storage_path VARCHAR(1000) NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    chunk_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_documents_course_id FOREIGN KEY (course_id) REFERENCES courses (id),
    CONSTRAINT fk_documents_topic_id FOREIGN KEY (topic_id) REFERENCES topics (id),
    CONSTRAINT fk_documents_uploaded_by_id FOREIGN KEY (uploaded_by_id) REFERENCES users (id)
);

CREATE INDEX idx_documents_course_id ON documents (course_id);
CREATE INDEX idx_documents_topic_id ON documents (topic_id);
CREATE INDEX idx_documents_uploaded_by_id ON documents (uploaded_by_id);

-- A text chunk of a document; embeddingId references the vector stored by the RAG service.
CREATE TABLE document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    content TEXT NOT NULL,
    token_count INTEGER,
    page_number INTEGER,
    embedding_id VARCHAR(100),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_document_chunks UNIQUE (document_id, chunk_index),
    CONSTRAINT fk_document_chunks_document_id FOREIGN KEY (document_id) REFERENCES documents (id)
);

CREATE INDEX idx_document_chunks_document_id ON document_chunks (document_id);
